#!/usr/bin/env python3
"""Generate a Markdown ingestion report from manifests.

Produces: security-brain/manifests/INGESTION_REPORT.md

Usage:
  python generate_ingestion_report.py
"""

import json
import sys
from datetime import datetime, timezone
from pathlib import Path

MANIFEST_DIR = "security-brain/manifests"
OUTPUT_FILE = f"{MANIFEST_DIR}/INGESTION_REPORT.md"


def _load_json_lines(path: Path) -> list:
    if not path.is_file():
        return []
    entries = []
    for line in path.read_text(encoding="utf-8").strip().split("\n"):
        if line.strip():
            try:
                entries.append(json.loads(line))
            except json.JSONDecodeError:
                pass
    return entries


def _count_by(dataset: list, key: str) -> dict:
    counts = {}
    for entry in dataset:
        val = entry.get(key, "unknown")
        counts[val] = counts.get(val, 0) + 1
    return dict(sorted(counts.items(), key=lambda x: -x[1]))


def main():
    man = Path(MANIFEST_DIR)
    man.mkdir(parents=True, exist_ok=True)

    ingested = _load_json_lines(man / "ingest_manifest.jsonl")
    errors = _load_json_lines(man / "ingest_errors.jsonl")

    total = len(ingested)
    err_count = len(errors)
    by_type = _count_by(ingested, "source_type")
    by_cat = _count_by(ingested, "category")
    recent = ingested[-10:] if ingested else []

    report = f"""# Ingestion Report

Generated: {datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")}

## Summary

| Metric | Count |
|--------|-------|
| Total files ingested | {total} |
| Errors | {err_count} |
| Source types | {len(by_type)} |
| Categories | {len(by_cat)} |

## By Source Type

| Type | Count |
|------|-------|
"""
    for t, c in by_type.items():
        report += f"| {t} | {c} |\n"

    report += "\n## By Category\n\n| Category | Count |\n|----------|-------|\n"
    for cat, c in by_cat.items():
        report += f"| {cat} | {c} |\n"

    if recent:
        report += "\n## Recent Ingestions\n\n"
        for entry in recent[:10]:
            title = entry.get("title", "?")
            stype = entry.get("source_type", "?")
            ts = entry.get("ingested_at", "?")
            report += f"- **{title}** ({stype}) — {ts}\n"

    report += f"\n## Manifest Files\n\n"
    report += f"- Manifest: `{MANIFEST_DIR}/ingest_manifest.jsonl` ({total} entries)\n"
    report += f"- Errors: `{MANIFEST_DIR}/ingest_errors.jsonl` ({err_count} entries)\n\n"

    report += "---\nGenerated by `scripts/generate_ingestion_report.py`\n"

    out = Path(OUTPUT_FILE)
    out.write_text(report, encoding="utf-8")
    print(f"Report written: {out} ({total} ingested, {err_count} errors)")


if __name__ == "__main__":
    main()
